Default: &defaults
  database: binah.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: binah_test.sqlite3
  <<: *defaults

Staging:
  database: binah_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: binah_production.sqlite3
  poolsize: 100
  <<: *defaults